version: '3.8'

services:
  flask:
    container_name: backend-flask
    build:
      context: .
      dockerfile: dockerfile.flask
    ports:
      - "5000:5000"
    networks:
      - iris-network
      
  streamlit:
    container_name: frontend-streamlit
    build:
      context: .
      dockerfile: dockerfile.streamlit
    ports:
      - "8501:8501"
    depends_on:
      - flask
    networks:
      - iris-network
  
networks:
  iris-network:
    driver: bridge
